language: elixir

elixir:
  - 1.5
otp_release:
  - 20.3

sudo: false

addons:
  postgresql: '9.4'

services:
  - postgresql


before_script:
- cp config/travis.exs config/test.secret.exs
- MIX_ENV=test mix local.rebar --force
- MIX_ENV=test mix local.hex --force
- MIX_ENV=test mix deps.get

install: true

jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - MIX_ENV=test mix do ecto.create, ecto.migrate
        - mix test
    - stage: 'Code Quality'
      name: "Excoveralls & Codecov"
      script: MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
    -
      name: "Credo"
      script: MIX_ENV=test mix credo
      after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - _build
    - deps
