language: elixir

elixir:
  - 1.5
otp_release:
  - 20.3

sudo: false

addons:
  postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.secret.exs
  - MIX_ENV=test mix local.rebar --force
  - MIX_ENV=test mix local.hex --force
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix do ecto.create, ecto.migrate

install: true

script:
  - mix test

cache:
  directories:
    - _build
    - deps
